import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
import { fireEvent, render, screen, waitFor } from "@testing-library/react"
const { refresh, upload } = vi.hoisted(() => ({ refresh: vi.fn(), upload: vi.fn() }))
vi.mock("next/navigation", () => ({ useRouter: () => ({ refresh }) }))
vi.mock("@/lib/r2/browser-upload", () => ({ uploadVideoParts: upload }))
import { LessonVideoUpload } from "@/components/admin/lesson-video-upload"
const props = { lessonId: "550e8400-e29b-41d4-a716-446655440001", updatedAt: "2026-10-03T12:00:00Z", attached: false }
beforeEach(() => { vi.clearAllMocks(); vi.stubGlobal("fetch", vi.fn()); upload.mockImplementation(async (_file, _parts, _signal, _sign, progress) => progress(100)) })
afterEach(() => vi.unstubAllGlobals())
describe("simple private video authoring", () => {
  it("opens the existing MP4 picker from the visible Choose video button", () => {
    const { container } = render(<LessonVideoUpload {...props} />)
    const input = container.querySelector('input[type="file"]')!
    const click = vi.spyOn(input as HTMLInputElement, "click")
    fireEvent.click(screen.getByRole("button", { name: "Choose video" }))
    expect(click).toHaveBeenCalledOnce()
    expect(input).toHaveAttribute("accept", "video/mp4,.mp4")
    expect(screen.getAllByText(/Maximum 1 GB/)[0]).toBeVisible()
    expect(fetch).not.toHaveBeenCalled()
  })
  it("shows upload progress then Ready, with no technical input or automatic publication", async () => {
    vi.mocked(fetch).mockResolvedValueOnce({ ok: true, json: async () => ({ uploadId: "upload", partBytes: 100, partCount: 1 }) } as Response)
      .mockResolvedValue({ ok: true, json: async () => ({ state: "ready" }) } as Response)
    const { container } = render(<LessonVideoUpload {...props} />)
    fireEvent.change(screen.getByLabelText("Choose video"), { target: { files: [new File(["mp4"], "video.mp4", { type: "video/mp4" })] } })
    expect(await screen.findByText(/Ready. Save/)).toBeVisible()
    expect(screen.getByRole("button", { name: "Save ready video" })).toBeEnabled()
    expect(container.querySelector('[name="object_key"], [name="bucket"], [name="endpoint"]')).toBeNull()
    expect(vi.mocked(fetch).mock.calls.map(call => JSON.parse(call[1]!.body as string).operation)).not.toContain("attach")
  })
  it("keeps a failed replacement attached and offers retry/cancel", async () => {
    vi.mocked(fetch).mockResolvedValueOnce({ ok: true, json: async () => ({ uploadId: "upload" }) } as Response)
    upload.mockRejectedValueOnce(new Error("Upload connection failed"))
    render(<LessonVideoUpload {...props} attached />)
    fireEvent.change(screen.getByLabelText("Replace video"), { target: { files: [new File(["mp4"], "video.mp4", { type: "video/mp4" })] } })
    expect(await screen.findByRole("alert")).toHaveTextContent("failed")
    expect(screen.getByText(/Current video ready/)).toBeVisible()
    expect(screen.getByRole("button", { name: "Retry upload" })).toBeEnabled()
    expect(screen.getByRole("button", { name: "Cancel upload" })).toBeEnabled()
    expect(refresh).not.toHaveBeenCalled()
  })
  it("re-verifies a recovered validating upload before offering save", async () => {
    vi.mocked(fetch).mockResolvedValue({ ok: true, json: async () => ({ state: "ready" }) } as Response)
    render(<LessonVideoUpload {...props} existingUpload={{ id: "upload", state: "validating", name: "video.mp4" }} />)
    expect(await screen.findByRole("button", { name: "Save ready video" })).toBeEnabled()
    expect(JSON.parse(vi.mocked(fetch).mock.calls[0][1]!.body as string).operation).toBe("complete")
    expect(upload).not.toHaveBeenCalled()
  })
  it("does not offer save when recovered object verification fails and can retry without a file", async () => {
    vi.mocked(fetch).mockResolvedValueOnce({ ok: false, json: async () => ({ error: "Object verification failed" }) } as Response)
      .mockResolvedValue({ ok: true, json: async () => ({ state: "ready" }) } as Response)
    render(<LessonVideoUpload {...props} attached existingUpload={{ id: "upload", state: "validating", name: "video.mp4" }} />)
    expect(await screen.findByRole("alert")).toHaveTextContent("Object verification failed")
    expect(screen.queryByRole("button", { name: "Save ready video" })).not.toBeInTheDocument()
    expect(screen.getByText(/Current video ready/)).toBeVisible()
    fireEvent.click(screen.getByRole("button", { name: "Retry upload" }))
    expect(await screen.findByRole("button", { name: "Save ready video" })).toBeEnabled()
    expect(upload).not.toHaveBeenCalled()
    expect(refresh).not.toHaveBeenCalled()
  })
  it("requires an explicit save before attaching a Ready upload", async () => {
    vi.mocked(fetch).mockResolvedValue({ ok: true, json: async () => ({ state: "ready", ok: true }) } as Response)
    render(<LessonVideoUpload {...props} existingUpload={{ id: "upload", state: "ready", name: "video.mp4" }} />)
    await waitFor(() => expect(screen.getByRole("button", { name: "Save ready video" })).toBeEnabled())
    expect(vi.mocked(fetch).mock.calls.every(call => JSON.parse(call[1]!.body as string).operation !== "attach")).toBe(true)
    fireEvent.click(screen.getByRole("button", { name: "Save ready video" }))
    await waitFor(() => expect(refresh).toHaveBeenCalled())
    expect(vi.mocked(fetch).mock.calls.some(call => JSON.parse(call[1]!.body as string).operation === "attach")).toBe(true)
  })
  it("confirms removal and submits the expected version for an atomic Draft change", async () => {
    vi.mocked(fetch).mockResolvedValue({ ok: true, json: async () => ({ ok: true }) } as Response)
    render(<LessonVideoUpload {...props} attached />)
    fireEvent.click(screen.getByRole("button", { name: "Remove video" }))
    expect(screen.getByText(/returns to Draft/)).toBeVisible(); expect(fetch).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole("button", { name: "Confirm remove video" }))
    await waitFor(() => expect(refresh).toHaveBeenCalled())
    expect(JSON.parse(vi.mocked(fetch).mock.calls[0][1]!.body as string)).toEqual({ operation: "remove", lessonId: props.lessonId, updatedAt: props.updatedAt })
  })
  it("cancels a durable unfinished upload without removing the attached video", async () => {
    vi.mocked(fetch).mockResolvedValue({ ok: true, json: async () => ({ ok: true }) } as Response)
    render(<LessonVideoUpload {...props} attached existingUpload={{ id: "upload", state: "uploading", name: "video.mp4" }} />)
    fireEvent.click(screen.getByRole("button", { name: "Cancel upload" }))
    expect(await screen.findByRole("status")).toHaveTextContent("current video is unchanged")
    expect(JSON.parse(vi.mocked(fetch).mock.calls[0][1]!.body as string).operation).toBe("cancel")
  })
  it("rejects unsuitable file claims before requesting permission", async () => {
    render(<LessonVideoUpload {...props} />)
    fireEvent.change(screen.getByLabelText("Choose video"), { target: { files: [new File(["not-mp4"], "video.exe", { type: "application/octet-stream" })] } })
    expect(screen.getByRole("alert")).toHaveTextContent("MP4 video up to 1 GB"); expect(fetch).not.toHaveBeenCalled()
  })
})
