import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
import { act, fireEvent, render, screen } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
vi.mock("@/actions/admin", () => ({ createLessonAction: vi.fn(), updateLessonAction: vi.fn(), createSectionAction: vi.fn(), updateSectionAction: vi.fn() }))
const { refresh, uploadFile } = vi.hoisted(() => ({ refresh: vi.fn(), uploadFile: vi.fn() }))
const router = { refresh }
vi.mock("next/navigation", () => ({ useRouter: () => router }))
vi.mock("@/lib/supabase/browser", () => ({ createSupabaseBrowserClient: () => ({ storage: { from: () => ({ uploadToSignedUrl: uploadFile }) } }) }))
import { createLessonAction, updateLessonAction } from "@/actions/admin"
import { LessonEditor } from "@/components/admin/lesson-editor"
import { LessonResources } from "@/components/admin/lesson-resources"
const id = "550e8400-e29b-41d4-a716-446655440001"
const lesson = { id, updated_at: "old-version", title: "Existing lesson", description: "Lesson text", lesson_type: "text" as const, status: "archived" as const, is_preview: true }
beforeEach(() => { vi.clearAllMocks(); uploadFile.mockResolvedValue({ error: null }) })

describe("non-technical lesson authoring", () => {
  it("replaces a legacy video using a normal URL with no technical controls", async () => {
    const user = userEvent.setup()
    vi.mocked(updateLessonAction).mockResolvedValue({ ok: true, message: "Lesson saved." })
    render(<LessonEditor lesson={{ ...lesson, lesson_type: "video", status: "draft", youtube_video_id: "dQw4w9WgXcQ", video_source: "legacy_youtube" }} content={{ legacyVideo: true, resources: [] }} />)
    expect(screen.getByText(/existing YouTube lesson keeps working/)).toBeVisible()
    await user.clear(screen.getByLabelText("YouTube video link"))
    await user.type(screen.getByLabelText("YouTube video link"), "https://youtu.be/dQw4w9WgXcQ")
    await user.click(screen.getByRole("button", { name: "Save lesson" }))
    expect(await screen.findByText("Lesson saved.")).toBeVisible()
    const data = vi.mocked(updateLessonAction).mock.calls[0][1]
    expect(data.get("youtube_url")).toBe("https://youtu.be/dQw4w9WgXcQ")
    expect(data.get("status")).toBe("draft")
    expect(screen.queryByText(/Mux|playback ID|asset ID|signing key/)).not.toBeInTheDocument()
  })
  it("removes the video link intentionally and selects Draft before saving", async () => {
    const user = userEvent.setup()
    vi.mocked(updateLessonAction).mockResolvedValue({ ok: true, message: "Lesson saved." })
    render(<LessonEditor lesson={{ ...lesson, lesson_type: "video", status: "published", youtube_video_id: "dQw4w9WgXcQ" }} />)
    expect(screen.getByLabelText("YouTube video link")).toHaveValue("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
    await user.click(screen.getByRole("button", { name: "Remove video link" }))
    expect(screen.getByLabelText("Visibility")).toHaveValue("draft")
    await user.click(screen.getByRole("button", { name: "Save lesson" }))
    expect(await screen.findByText("Lesson saved.")).toBeVisible()
    expect(vi.mocked(updateLessonAction).mock.calls[0][1].get("youtube_url")).toBe("")
  })
  it("asks only for relevant lesson controls and retains archived/preview semantics", () => {
    const { container } = render(<LessonEditor lesson={lesson} />)
    expect(screen.getByLabelText("Visibility")).toHaveValue("archived")
    expect(screen.getByLabelText("Lesson text")).toHaveValue("Lesson text")
    expect(screen.getByText(/Access still requires active enrollment/)).toBeInTheDocument()
    expect(container.querySelector('[name="slug"], [name="position"], [name="duration_seconds"], [name="mux_asset_id"], [name="mux_playback_id"]')).toBeNull()
  })
  it("preserves edited text after save failure", async () => {
    const user = userEvent.setup()
    vi.mocked(updateLessonAction).mockResolvedValue({ ok: false, message: "We could not save your changes. Please try again." })
    render(<LessonEditor lesson={lesson} />)
    await user.type(screen.getByLabelText("Lesson text"), " More content")
    await user.click(screen.getByRole("button", { name: "Save lesson" }))
    expect(await screen.findByRole("alert")).toHaveTextContent("Please try again")
    expect(screen.getByLabelText("Lesson text")).toHaveValue("Lesson text More content")
  })
  it("creates a draft without asking for technical values", async () => {
    const user = userEvent.setup()
    vi.mocked(createLessonAction).mockResolvedValue({ ok: true, message: "Lesson created." })
    render(<LessonEditor sections={[{ id, title: "Introduction" }]} />)
    expect(screen.getByText(/Draft — hidden from students\. Add your content/)).toBeInTheDocument()
    await user.type(screen.getByLabelText("Lesson title"), "First lesson")
    await user.click(screen.getByRole("button", { name: "Create lesson" }))
    expect(await screen.findByRole("status")).toHaveTextContent("Lesson created.")
    const data = vi.mocked(createLessonAction).mock.calls[0][1]
    expect(data.get("status")).toBe("draft")
    expect(data.get("section_id")).toBe(id)
    expect(data.has("slug")).toBe(false)
  })
  it("explains independent live-class scheduling", async () => {
    const user = userEvent.setup()
    render(<LessonEditor lesson={lesson} />)
    await user.selectOptions(screen.getByLabelText("Content type"), "live_class")
    expect(screen.getByRole("link", { name: "Live Classes" })).toHaveAttribute("href", "/admin/live-classes")
    expect(screen.getByLabelText("Description")).toBeInTheDocument()
  })
  it("retries attaching an uploaded private file without uploading it twice", async () => {
    const user = userEvent.setup()
    const fetch = vi.fn().mockResolvedValueOnce({ ok: true, json: async () => ({ path: "internal/private-object", token: "upload-token" }) })
      .mockResolvedValueOnce({ ok: false }).mockResolvedValueOnce({ ok: true, json: async () => ({ ok: true }) })
    vi.stubGlobal("fetch", fetch)
    render(<LessonResources lessonId={id} resources={[]} external={false} />)
    await user.upload(screen.getByLabelText("Attach a file"), new File(["pdf-content"], "Handout.pdf", { type: "application/pdf" }))
    expect(await screen.findByRole("alert")).toHaveTextContent("Retry attaching")
    expect(screen.queryByText("internal/private-object")).not.toBeInTheDocument()
    await user.click(screen.getByRole("button", { name: "Retry attaching uploaded file" }))
    expect(await screen.findByRole("status")).toHaveTextContent("File attached securely.")
    expect(uploadFile).toHaveBeenCalledTimes(1)
    expect(refresh).toHaveBeenCalled()
  })
  it("edits existing external links and validates credentials in URLs", async () => {
    const user = userEvent.setup()
    const fetch = vi.fn()
    vi.stubGlobal("fetch", fetch)
    render(<LessonResources lessonId={id} external resources={[{ id, title: "External video", resource_type: "external_link", url: "https://example.com/video" }]} />)
    await user.click(screen.getByRole("button", { name: "Edit link" }))
    expect(screen.getByLabelText("Link URL")).toHaveValue("https://example.com/video")
    await user.clear(screen.getByLabelText("Link URL"))
    await user.type(screen.getByLabelText("Link URL"), "https://user:pass@example.com")
    await user.click(screen.getByRole("button", { name: "Save link" }))
    expect(await screen.findByRole("alert")).toHaveTextContent("without a username or password")
    expect(fetch).not.toHaveBeenCalled()
  })
  it.each(["video", "text", "pdf_resource", "external_resource", "live_class"] as const)("shows appropriate content controls for %s", type => {
    render(<LessonEditor lesson={{ ...lesson, lesson_type: type }} content={{  resources: [] }} />)
    expect(screen.queryByLabelText("Choose video") !== null).toBe(type === "video")
    expect(screen.queryByLabelText("Link URL") !== null).toBe(type === "external_resource")
    expect(screen.queryByLabelText("Lesson text") !== null).toBe(type === "text")
    expect(screen.queryByLabelText("Attach a file") !== null).toBe(type !== "external_resource")
    if (type === "live_class") expect(screen.getByRole("link", { name: "Live Classes" })).toHaveAttribute("href", "/admin/live-classes")
  })
  it("requires saving a changed type before uploading and restores controls when reverted", async () => {
    const user = userEvent.setup()
    render(<LessonEditor lesson={{ ...lesson, lesson_type: "video" }} content={{  resources: [] }} />)
    expect(screen.getByLabelText("Choose video")).toBeVisible()
    await user.selectOptions(screen.getByLabelText("Content type"), "external_resource")
    expect(screen.getByRole("status")).toHaveTextContent("Save lesson to confirm")
    expect(screen.queryByLabelText("Choose video")).not.toBeInTheDocument()
    expect(screen.queryByLabelText("Link URL")).not.toBeInTheDocument()
    await user.selectOptions(screen.getByLabelText("Content type"), "video")
    expect(screen.getByLabelText("Choose video")).toBeVisible()
  })
  it.each(["pdf_resource", "external_resource"])("explains how to attach %s after creating a draft", async type => {
    const user = userEvent.setup()
    render(<LessonEditor sections={[{ id, title: "Introduction" }]} />)
    await user.selectOptions(screen.getByLabelText("Content type"), type)
    expect(screen.getByText(/Create this lesson as a draft first/)).toBeVisible()
    expect(screen.queryByLabelText("Upload video")).not.toBeInTheDocument()
  })
  it("adds an external link with the resource API", async () => {
    const user = userEvent.setup()
    const fetch = vi.fn().mockResolvedValue({ ok: true, json: async () => ({ ok: true }) })
    vi.stubGlobal("fetch", fetch)
    render(<LessonResources lessonId={id} external resources={[]} />)
    await user.type(screen.getByLabelText("Link title"), "Watch the lesson")
    await user.type(screen.getByLabelText("Link URL"), "https://example.com/video")
    await user.click(screen.getByRole("button", { name: "Add link" }))
    expect(await screen.findByRole("status")).toHaveTextContent("Link saved")
    expect(JSON.parse(fetch.mock.calls[0][1].body)).toEqual({ lessonId: id, operation: "link", title: "Watch the lesson", url: "https://example.com/video" })
    expect(refresh).toHaveBeenCalled()
  })
  it.each(["javascript:alert(1)", "ftp://example.com/file", "https://user:pass@example.com"])("rejects unsafe external content %s", async url => {
    const user = userEvent.setup()
    const fetch = vi.fn()
    vi.stubGlobal("fetch", fetch)
    render(<LessonResources lessonId={id} external resources={[]} />)
    await user.type(screen.getByLabelText("Link title"), "Lesson link")
    fireEvent.change(screen.getByLabelText("Link URL"), { target: { value: url } })
    fireEvent.submit(screen.getByRole("button", { name: "Add link" }).closest("form")!)
    expect(screen.getByRole("alert")).toHaveTextContent("complete http:// or https:// link")
    expect(fetch).not.toHaveBeenCalled()
  })
  it("shows file uploading and ready states without displaying storage paths", async () => {
    const user = userEvent.setup()
    let complete!: (value: { error: null }) => void
    uploadFile.mockReturnValue(new Promise(resolve => { complete = resolve }))
    vi.stubGlobal("fetch", vi.fn().mockResolvedValueOnce({ ok: true, json: async () => ({ path: "private/path", token: "token" }) }).mockResolvedValueOnce({ ok: true, json: async () => ({ ok: true }) }))
    render(<LessonResources lessonId={id} external={false} resources={[]} />)
    await user.upload(screen.getByLabelText("Attach a file"), new File(["pdf"], "Handout.pdf", { type: "application/pdf" }))
    expect(screen.getByRole("status")).toHaveTextContent("Uploading file")
    expect(screen.getByLabelText("Attach a file")).toBeDisabled()
    await act(async () => complete({ error: null }))
    expect(await screen.findByRole("status")).toHaveTextContent("File attached securely")
    expect(screen.queryByText("private/path")).not.toBeInTheDocument()
    expect(screen.getByLabelText("Attach a file")).toBeEnabled()
  })
  it("rejects unsupported and oversized files before upload", () => {
    const fetch = vi.fn()
    vi.stubGlobal("fetch", fetch)
    render(<LessonResources lessonId={id} external={false} resources={[]} />)
    const input = screen.getByLabelText("Attach a file")
    fireEvent.change(input, { target: { files: [new File(["html"], "file.html", { type: "text/html" })] } })
    expect(screen.getByRole("alert")).toHaveTextContent("up to 25 MB")
    const large = new File(["pdf"], "large.pdf", { type: "application/pdf" })
    Object.defineProperty(large, "size", { value: 26 * 1024 * 1024 })
    fireEvent.change(input, { target: { files: [large] } })
    expect(fetch).not.toHaveBeenCalled()
    expect(uploadFile).not.toHaveBeenCalled()
  })
  it("keeps a failed link editable without exposing server errors", async () => {
    const user = userEvent.setup()
    vi.stubGlobal("fetch", vi.fn().mockResolvedValue({ ok: false, status: 403, json: async () => ({ error: "raw database error" }) }))
    render(<LessonResources lessonId={id} external resources={[]} />)
    await user.type(screen.getByLabelText("Link title"), "My link")
    await user.type(screen.getByLabelText("Link URL"), "https://example.com")
    await user.click(screen.getByRole("button", { name: "Add link" }))
    expect(await screen.findByRole("alert")).toHaveTextContent("could not save the link")
    expect(screen.getByLabelText("Link title")).toHaveValue("My link")
    expect(screen.queryByText("raw database error")).not.toBeInTheDocument()
  })
})

afterEach(() => vi.unstubAllGlobals())
